version: "3.8"
services:
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mini_project
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

